# This file was generated by GoReleaser. DO NOT EDIT.
cask "ondx" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "1eff6982cb10ab1e49a373c4422e8e4f8cf1f01542234fb6e5b99bb12908480c"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c76b05a4989a71b27a63351086bdac6e275a24a9e21496856dfab5f5a0f9d0c"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "13598a7eb7c39560da27da1e7c15ca493f9affbe9ae7b73b5d4dcbefd7ece70c"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "033c6792a9b7007010dcc276f416542081c1c5a56967878e0e6223045832698a"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_linux_amd64.tar.gz"
    end
  end

  name "ondx"
  desc "OpenNDX management CLI"
  homepage "https://github.com/openndx/openndx-core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ondx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ondx"]
    end
  end

  # No zap stanza required
end
