# This file was generated by GoReleaser. DO NOT EDIT.
cask "ondx" do
  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "fa48ff832a56c34fdf7429f84ebbe08bbba253b7c4b493be33ad3f86bf8aa15a"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9850a1c656418e5994ed68c0ff5d09b873b8346dabcd771b15af54ec21b30032"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "53219047a9dae528d4bcca9e6ff4fb34ce9572144d3c81b2db58dac79c21b768"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1865618b0bf484dc17f1120d703b5010ecc9e87a13017f79c97d94513eba35fc"
      url "https://github.com/mushrafmim/openndx/releases/download/v#{version}/ondx_linux_amd64.tar.gz"
    end
  end

  name "ondx"
  desc "OpenNDX management CLI"
  homepage "https://github.com/openndx/openndx-core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ondx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ondx"]
    end
  end

  # No zap stanza required
end
